#!/bin/bash -x

#####################################
# Get settings from the configuration file
#
# An example configuration:
# 
# SITE=site-name
# STOP=site-container:site-db
# WORKDIR=/path/to/workdir
# BACKUPDIR=/path/to/backups
# VOLUMES=volume1:volume2
# DATABASE_CONTAINER=site-db
# DATABASE_NAME=database
# ARCHIVE=content-directory:images-directory
# SYNC=.env:bind-mount.file
#####################################

if [ -f "$1" ]; then
	while read -r line; do export "${line?}"; done < $1
else
	echo "USE: ./docker-backup CONFIG_FILE"
	exit 1;
fi

if [ -z "${SITE}" ] || [ -z "${WORKDIR}" ] || [ -z "${BACKUPDIR}" ]; then
	echo "Missing required configuration settings"
	exit 1;
fi

DIR="$BACKUPDIR/$SITE/$(date -I)_$SITE"
mkdir -p "$DIR"

#####################################
# Stop containers
#####################################

if [ -n "$STOP" ]; then
	IFS=":" read -a containers <<< "$STOP"
	for i in "${containers[@]}"
	do
	 docker stop "$i"
	done
fi

#####################################
# Backup volumes
#####################################
if [ -n "${VOLUMES}" ]; then
	IFS=":" read -a volume_arr <<< "$VOLUMES"
	for i in "${volume_arr[@]}"
	do
	 mkdir "$DIR"/"$i"
	 docker run --rm -v $i:/backup_source -v $DIR:/backup_target busybox tar -czvf /backup_target/$i.tar.gz /backup_source
	done
fi

#####################################
# Backup Database
#####################################
if [ -n "${DATABASE_CONTAINER}" ] && [ -n "${DATABASE_NAME}" ]; then
	docker exec -e DB="$DATABASE_NAME" "$DATABASE_CONTAINER" sh -c 'mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --lock-all-tables $DB' > $DIR/"$(date -I)"$DB.sql && gzip $DIR/"$(date -I)"$DB.sql
fi

#####################################
# Archive local and bind mounted files
#####################################

if [ -n "${ARCHIVE}" ]; then 
	IFS=":" read -a path_arr <<< "$ARCHIVE"
	for i in "${path_arr[@]}"
	do
		out=$(basename $i)
		if [ ${out:0:1} == "." ]; then out="${out#*.}"; fi
		tar -czvf "$DIR"/"$out".tar.gz "$WORKDIR$i"
	done
fi

#####################################
# Sync local files
#####################################

if [ -n "${SYNC}" ]; then
	IFS=":" read -a path_arr <<< "$SYNC"
	for i in "${path_arr[@]}"
	do
		cp -au "$WORKDIR/$i" "$BACKUPDIR/$SITE/"
	done
fi

#####################################
# Restart containers
#####################################

if [ -n "$STOP" ]; then
	IFS=":" read -a containers <<< "$STOP"
	for i in "${containers[@]}"
	do
	 docker start "$i"
	done
fi
