#!/usr/bin/bash

print_usage() { echo "Usage: $(basename $0) -t TITLE -y YEAR [-o ORGANISATION] [-a AUTHOR] -f PDF_FILE"; }

while getopts "t:o:a:y:f:" opt; do
	
	if [[ $OPTARG = -* ]]; then
		echo "Check argument syntax. Possible missing argument for option ${opt}.";
		echo "Got \"${OPTARG}\" for ${opt}.";
		exit 1;
	fi

    case "${opt}" in
        t)	TITLE=${OPTARG};
			;;
        o)	ORG=${OPTARG};
			;;
        a)	AUTHOR=${OPTARG};
			;;
        y)	YEAR=${OPTARG};
			;;
        f)	DOC=${OPTARG};
			;;
		\?) print_usage;
            exit 1
            ;;
		:)	echo "Missing option argument for -$OPTARG";
            exit 1
            ;;
    esac
done

if ((OPTIND == 1))
then
    echo "No options specified.";
	print_usage;
	exit 1;
fi

shift $((OPTIND -1))

#These parameters are required, so we exit if they aren't set
if [ -z "$TITLE" ] || [ -z "$YEAR" ] || [ -z "$DOC" ]; then
	echo "Required options missing.";
	print_usage;
	exit 1;
fi

if [ ! -f $DOC ]; then
	echo "Invalid file provided. Check that -f option refers to a valid file.";
	exit 1;
elif [[ ! $(file --mime-type -b "$DOC") == "application/pdf" ]]; then
	echo "File $DOC is not a PDF file.";
	exit 1;
fi

DATATEX="{\fbc Title:} ${TITLE} \\\\"

if [ ! -z "$ORG" ]; then
    DATATEX="{$DATATEX}
        {\fbc Organisation:} ${ORG} \\\\"
fi

if [ ! -z "$AUTHOR" ]; then
    DATATEX="{$DATATEX}
        {\fbc Author:} ${AUTHOR} \\\\"
fi

DATATEX="{$DATATEX}
        {\fbc Date:} ${YEAR}\par"

##Add trailing page
PAGETEX="\documentclass{article}

\usepackage[colorlinks]{hyperref}
 \hypersetup{urlcolor=[rgb]{0.258,0.545,0.792}}

\usepackage[default]{opensans}

\def\fbc{\fontseries{bc}\selectfont}

\setlength{\parindent}{0em}

\begin{document}
\thispagestyle{empty}

{\fontseries{lc}\fontsize{20pt}{26pt}\selectfont
${DATATEX}
}

\vspace{1.5cm}

\fontsize{16pt}{20pt}\selectfont
Downloaded from the Irish Left Archive. \\\\
Visit \href{https://www.leftarchive.ie}{www.leftarchive.ie} \\\\

\vspace{1.5cm}

\fontsize{12pt}{16pt}\selectfont
\emph{The Irish Left Archive is provided as a non-commercial historical resource, open to all, and has reproduced this document as an accessible digital reference. Copyright remains with its original authors. If used on other sites, we would appreciate a link back and reference to the Irish Left Archive, in addition to the original creators. For re-publication, commercial, or other uses, please contact the original owners. If documents provided to the Irish Left Archive have been created for or added to other online archives, please inform us so sources can be credited.}

\end{document} 
"

echo "${PAGETEX}" > tex_tmp.tex

pdflatex -interaction=batchmode tex_tmp.tex

mv ${DOC} pdf_tmp.pdf
gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/default -sOutputFile=${DOC} pdf_tmp.pdf tex_tmp.pdf

#Add org as author, if no author specified.
if [ -z "$AUTHOR" ]; then
    M_AUTH=${ORG}
else
    M_AUTH=${AUTHOR}
fi

exiftool -Title="${TITLE}" -Author="${M_AUTH}" ${DOC}

gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -dFirstPage=1 -dLastPage=1 -sOutputFile=page1.pdf ${DOC}
convert page1.pdf -filter Lanczos -define filter:blur=.9891028367558475 -distort Resize 1600x "${DOC%%.*}".jpeg

#Cleanup
rm page1.* pdf_tmp.pdf tex_tmp.* ${DOC}_original
